### PR TITLE
adjustments + story expanded with comparison + horizontal scroll

### PR DESCRIPTION
**Pull request by Rogermax**
## 🚪 Why?

To improve UX

## 🔑 What?

Add opacity to new scrollbar component

## 📸 Screenshots

https://github.com/factorialco/factorial-one/assets/2633254/bc5a3a87-ff2b-4b29-ae89-e2ddf8feeb2a

Also Added horizontal scroll

https://github.com/factorialco/factorial-one/assets/2633254/50b4b590-d89a-4583-88b3-ed5d92713594

### CODE REVIEW

**Review by josepjaume — APPROVED** [review]
Amazing job, love it!!

**Comment by josepjaume** [comment]
Looks like you haven't used the prettier extension. You can fix it by running `npm run prettier:format` regardless :)

**Comment by josepjaume** [comment]
Oh BTW this project uses "npm", not "pnpm". Should document this better!

**Comment by Rogermax** [comment]
pnpm doesn't breaks anything (I think) just to avoid problems we have to tell prettier to ignore that file (this was the problem)

**Pull request merged**
