### PR TITLE
Create more flexible CategoryBarSection component

### PR DESCRIPTION
**Pull request by sauldom102**
## 🔑 What?

Create more flexible CategoryBarSection component.

## 🚪 Why?

We have a ProgressSection component but it doesn't cover all of the cases that we can see on Figma.

## 🏡 Context

- [💼 Jira](https://factorialmakers.atlassian.net/browse/FCT-18541)

## 👁️ Visual proof

Screenshot 2024-09-06 at 10 32 53

Screenshot 2024-09-06 at 10 33 08

### CODE REVIEW

**Comment by nlopin** [comment]
Could you give me some context, please?

* As I understood, we create a `CategoryBarSection` as a more flexible alternative for some other component. What is the name of this component?
* I see in the [Employee Profile in Figma](https://www.figma.com/design/9pLsRzdinid0ha0qRWta2D/Employee-Profile?node-id=1435-21401&node-type=INSTANCE&m=dev) two bar charts. Are there more?

**Comment by sauldom102** [comment]
> Could you give me some context, please?
> 
> * As I understood, we create a `CategoryBarSection` as a more flexible alternative for some other component. What is the name of this component?
> * I see in the [Employee Profile in Figma](https://www.figma.com/design/9pLsRzdinid0ha0qRWta2D/Employee-Profile?node-id=1435-21401&node-type=INSTANCE&m=dev) two bar charts. Are there more?

The other component is `ProgressSection`

**Review by sauldom102 — COMMENTED** [review]
@nlopin we have these bars too:

Screenshot 2024-09-06 at 13 42 37

**Comment by nlopin** [comment]
Can we then replace the `ProgressSection` implementation with yours and avoid creating a new component?

I didn't get visual differences between those two components, if we leave both components in the design system, it won't be clear which one a developer should pick.

**Review by RamProg — APPROVED** [review]
nice! minor comment

**Pull request merged**
