### PR TITLE
change theme of storybook

### PR DESCRIPTION
**Pull request by Rogermax**
## 🚪 Why?

Changing theme in storybook just change components.. I would like that main colors of storybook change too

## 🔑 What?

Add configuration files to .storybook to try to achieve it

## Screenshot

https://github.com/user-attachments/assets/bf58e5b4-5539-49c5-8ebc-b1c6d6bb9099

### CODE REVIEW

**Review by josepjaume — APPROVED** [review]
This is cool!

**Comment by josepjaume** [comment]
Hey @Rogermax I see this is still a draft. Should we merge it?

**Comment by Rogermax** [comment]
> Hey @Rogermax I see this is still a draft. Should we merge it?

It is a WIP I couldn't achieve what i was looking for, yet.

**Comment by dani-moreno** [comment]
Ah whoa, this is a cool idea. Let me know if I can help you @Rogermax! 🫶

**Comment by Rogermax** [comment]
Feel free to owned it, I can't take it back until finishing the Hacktorial

**Comment by josepjaume** [comment]
@Rogermax it would be aswesome if you could finish this! ❤️

**Pull request merged**
